 mutation InsertOneLink($platform_name: String!, $link: String!, $profile_id: Int!) {
    insert_links_one(object: {platform_name: $platform_name, link: $link, profile_id: $profile_id}, on_conflict: {constraint: links_link_key, update_columns: [created_at]}) {
      id_
      platform_name
      link
      profile_id
    }
  }